version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build: .
    container_name: streamlit_container
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
